import React from 'react';
import { Link } from 'react-router-dom';
import { Button } from '../components/Button';

export const Terms: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-12">
      <div className="mb-8 border-b border-neon-blue pb-4">
        <h1 className="text-4xl font-display font-bold text-white uppercase tracking-widest">Master Protocol Agreement</h1>
        <p className="text-neon-blue font-mono text-xs">LAST UPDATED: CURRENT_CYCLE</p>
      </div>

      <div className="space-y-8 font-mono text-sm text-gray-300 bg-black border border-gray-800 p-8 shadow-[0_0_30px_rgba(0,0,0,0.5)]">
        
        <section>
          <h2 className="text-lg text-white font-bold uppercase mb-2 border-l-4 border-neon-green pl-3">1. Platform Structure & Fees</h2>
          <p className="leading-relaxed">
            Social Swarm ("The Platform") operates on a zero-overhead model for listing. 
            <br/><br/>
            <strong>A. No Listing Fees:</strong> Businesses pay $0.00 to list products.
            <br/>
            <strong>B. Commission-Only:</strong> Payments are only triggered upon a verified sale.
            <br/>
            <strong>C. The Split:</strong> Social Swarm retains a fixed percentage (30%) of the Total Commission agreed upon by the business to maintain network integrity, with the remaining majority (70%) paid directly to the Creator.
          </p>
        </section>

        <section>
          <h2 className="text-lg text-white font-bold uppercase mb-2 border-l-4 border-neon-green pl-3">2. Affiliate Link Validation & Usage</h2>
          <p className="leading-relaxed">
             <strong>A. Business Responsibility:</strong> The Business is solely responsible for generating, assigning, and validating unique affiliate links for each creator. The Platform does not generate external affiliate links.
             <br/>
             <strong>B. Creator Usage:</strong> Creators must exclusively use the link provided via the platform dashboard for tracking purposes.
             <br/>
             <strong>C. Compliance:</strong> Creators agree to adhere strictly to the Advertising Guidelines and Prohibited Practices outlined by the Business for each campaign. Violation (e.g., making false health claims) results in immediate contract termination and forfeiture of pending payouts.
          </p>
        </section>

        <section>
          <h2 className="text-lg text-neon-red font-bold uppercase mb-2 border-l-4 border-neon-red pl-3">3. Non-Bypass & Non-Circumvention (Strict Enforcement)</h2>
          <p className="leading-relaxed">
            <strong>A. Prohibition:</strong> Users (Businesses and Creators) are strictly prohibited from using the Platform to identify partners and then conducting transactions off-platform to avoid Platform Fees.
            <br/>
            <strong>B. Penalty:</strong> If a bypass attempt is detected:
            <ul className="list-disc pl-5 mt-2 mb-2">
                <li>The Business forfeits ALL pending sales revenue held in escrow or owed.</li>
                <li>The Creator forfeits ALL pending payouts.</li>
                <li>Both parties will be permanently blacklisted from the network.</li>
            </ul>
            <strong>C. Clawback:</strong> Social Swarm reserves the right to pursue legal action to recover lost revenue (Platform Fees) resulting from any circumvention of this protocol.
          </p>
        </section>

        <section>
          <h2 className="text-lg text-white font-bold uppercase mb-2 border-l-4 border-neon-green pl-3">4. Sales Reporting Protocol</h2>
          <p className="leading-relaxed">
            <strong>A. Mandatory Reporting:</strong> Business Entities are required to manually report sales generated by Swarm Affiliate Codes.
            <br/>
            <strong>B. Integrity:</strong> Failure to report valid sales is a violation of this protocol and may result in a permanent ban and blacklisting of the Business Entity.
          </p>
        </section>

        <section>
          <h2 className="text-lg text-white font-bold uppercase mb-2 border-l-4 border-neon-green pl-3">5. Tax Liability & Contractor Status</h2>
          <p className="leading-relaxed">
            <strong>A. Independent Contractors:</strong> All Creators (Netrunners) act as independent contractors. No employment relationship exists between the Creator and Social Swarm and the Business.
            <br/>
            <strong>B. Tax Responsibility:</strong> 
            Social Swarm does <u>NOT</u> issue Form 1099 or W-9 documentation. The Business pays the Creator directly via the Platform's interface.
            <br/>
            <span className="text-neon-yellow bg-yellow-900/20 p-1 block mt-2 border border-neon-yellow">
              WARNING: Both Businesses and Creators are solely responsible for reporting their own income and expenses to relevant tax authorities. Social Swarm functions strictly as a connection and tracking protocol, not a financial employer.
            </span>
          </p>
        </section>

      </div>

      <div className="mt-8 text-center">
        <Link to="/">
          <Button variant="secondary">Acknowledge & Return</Button>
        </Link>
      </div>
    </div>
  );
};